In [25]:
    import numpy as np
    import pandas as pd
    import random
    from sklearn.metrics import mean_squared_error, r2_score



    rand_state = {
        'Rice': 64, #10
        'Maize': 64, #46
        'Cotton':63,#66
        'Groundnut':54, #12
        'Jowar':62, #66
        'Soyabean':74, #98 , 34
        'Urad':38, #76
        'Moong':102, #66
        'Tur':46  #96
    }

    crop={
        1:'Rice',
        2:'Maize',
        3:'Cotton',
        4:'Groundnut',
        5:'Jowar',
        6:'Soyabean',
        7:'Urad',
        8:'Moong',
        9:'Tur'

    }

    df = pd.read_csv('dataset/Data_Main8_with_CP_DoP_InP_ImP_ExP_Single_Moong.csv')
    print(df)
    all_commodities = {}
    cnt = 0

    for i in range(len(df)):
        if df.loc[i]['Crops'] not in all_commodities:
            all_commodities[df.loc[i]['Crops']] = cnt
            cnt += 1

    all_years = {}
    cnt = 0

    for i in range(len(df)):
        if df.loc[i]['Year'] not in all_years:
            all_years[df.loc[i]['Year']] = cnt
            cnt += 1
            
    all_Cost_Production = {}
    cnt = 0

    for i in range(len(df)):
        if df.loc[i]['Cost_Production'] not in all_Cost_Production:
            all_Cost_Production[df.loc[i]['Cost_Production']] = cnt
            cnt += 1
            
    all_Domastic_Price = {}
    cnt = 0

    for i in range(len(df)):
        if df.loc[i]['Domastic_Price'] not in all_Domastic_Price:
            all_Domastic_Price[df.loc[i]['Domastic_Price']] = cnt
            cnt += 1
            
    all_International_Price = {}
    cnt = 0

    for i in range(len(df)):
        if df.loc[i]['International_Price'] not in all_International_Price:
            all_International_Price[df.loc[i]['International_Price']] = cnt
            cnt += 1       
    all_Import = {}
    cnt = 0

    for i in range(len(df)):
        if df.loc[i]['Import'] not in all_Import:
            all_Import[df.loc[i]['Import']] = cnt
            cnt += 1
    all_Export = {}
    cnt = 0

    for i in range(len(df)):
        if df.loc[i]['Export'] not in all_Export:
            all_Export[df.loc[i]['Export']] = cnt
            cnt += 1
    
    print(all_commodities)
    print(all_years)
    print(all_Cost_Production)
    print(all_Domastic_Price)
    print(all_International_Price)
    print(all_Import)
    print(all_Export)
   

    x = df[['Crops', 'Year', 'Cost_Production', 'Domastic_Price', 'International_Price', 'Import','Export']]  # input features
    y = df[['MSP']]  # to be predicted by model

    x = np.array(x)
    y = np.array(y)

    # convert x and y to integer values

    for i in range(len(x)):
        x[i][0] = all_commodities[x[i][0]]
        x[i][1] = all_years[x[i][1]]
        x[i][2] = all_Cost_Production[x[i][2]]
        x[i][3] = all_Domastic_Price[x[i][3]]
        x[i][4] = all_International_Price[x[i][4]]
        x[i][5] = all_Import[x[i][5]]
        x[i][6] = all_Export[x[i][6]]
    # convert x and y from object to int

    x = np.array(x, dtype='float32')
    y = np.array(y, dtype='float32')

    y = y.ravel()

    np.unique(y, return_counts=True)
    for i in range(100):
        from sklearn.model_selection import train_test_split
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)

        from sklearn.linear_model import LinearRegression

        regressor = LinearRegression()
        regressor.fit(x, y)

        y_pred = regressor.predict(x_test)
        R2 = r2_score(y_test, y_pred)
        #print("\n R2:", R2)
        #print("\n MSE:", mean_squared_error(y_test, y_pred))
        print("\n RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)),"=",i)

    Crops     Year  Cost_Production  Domastic_Price  International_Price  \
0   Moong  2010-11         10321.80         4088.00              4821.25
1   Moong  2011-12         12515.81         4221.50              5151.50
2   Moong  2012-13         15366.75         4550.50              4820.00
3   Moong  2013-14         16453.26         5390.75              5435.25
4   Moong  2014-15         16611.90         6505.75              6982.50
5   Moong  2015-16         18792.50         7371.25              7440.00
6   Moong  2016-17         20260.83         6037.00              6153.75
7   Moong  2017-18         20429.00         4861.50              5362.75
8   Moong  2018-19         20987.21         4968.25              5923.75
9   Moong  2019-20         21361.87         5460.75              6611.50
10  Moong  2020-21         22001.23         6637.75              8097.25

    Import  Export   MSP
0     63.5   117.4  3170
1     89.0   187.2  3500
2    117.7   232.4  4400
3    109.7   268.7  4500
4    144.8   245.5  4600
5    163.3   222.5  4850
6    185.3   233.6  5225
7    175.8   258.7  5575
8    161.9   283.5  6975
9    169.7   262.0  7050
10   144.1   251.9  7196
{'Moong': 0}
{'2010-11': 0, '2011-12': 1, '2012-13': 2, '2013-14': 3, '2014-15': 4, '2015-16': 5, '2016-17': 6, '2017-18': 7, '2018-19': 8, '2019-20': 9, '2020-21': 10}
{10321.8: 0, 12515.81: 1, 15366.75: 2, 16453.26: 3, 16611.9: 4, 18792.5: 5, 20260.83: 6, 20429.0: 7, 20987.21: 8, 21361.87: 9, 22001.23: 10}
{4088.0: 0, 4221.5: 1, 4550.5: 2, 5390.75: 3, 6505.75: 4, 7371.25: 5, 6037.0: 6, 4861.5: 7, 4968.25: 8, 5460.75: 9, 6637.75: 10}
{4821.25: 0, 5151.5: 1, 4820.0: 2, 5435.25: 3, 6982.5: 4, 7440.0: 5, 6153.75: 6, 5362.75: 7, 5923.75: 8, 6611.5: 9, 8097.25: 10}
{63.5: 0, 89.0: 1, 117.7: 2, 109.7: 3, 144.8: 4, 163.3: 5, 185.3: 6, 175.8: 7, 161.9: 8, 169.7: 9, 144.1: 10}
{117.4: 0, 187.2: 1, 232.4: 2, 268.7: 3, 245.5: 4, 222.5: 5, 233.6: 6, 258.7: 7, 283.5: 8, 262.0: 9, 251.9: 10}

 RMSE: 464.69412 = 0

 RMSE: 464.69412 = 1

 RMSE: 464.69412 = 2

 RMSE: 464.69412 = 3

 RMSE: 464.69412 = 4

 RMSE: 464.69412 = 5

 RMSE: 464.69412 = 6

 RMSE: 464.69412 = 7

 RMSE: 464.69412 = 8

 RMSE: 464.69412 = 9

 RMSE: 464.69412 = 10

 RMSE: 464.69412 = 11

 RMSE: 464.69412 = 12

 RMSE: 464.69412 = 13

 RMSE: 464.69412 = 14

 RMSE: 464.69412 = 15

 RMSE: 464.69412 = 16

 RMSE: 464.69412 = 17

 RMSE: 464.69412 = 18

 RMSE: 464.69412 = 19

 RMSE: 464.69412 = 20

 RMSE: 464.69412 = 21

 RMSE: 464.69412 = 22

 RMSE: 464.69412 = 23

 RMSE: 464.69412 = 24

 RMSE: 464.69412 = 25

 RMSE: 464.69412 = 26

 RMSE: 464.69412 = 27

 RMSE: 464.69412 = 28

 RMSE: 464.69412 = 29

 RMSE: 464.69412 = 30

 RMSE: 464.69412 = 31

 RMSE: 464.69412 = 32

 RMSE: 464.69412 = 33

 RMSE: 464.69412 = 34

 RMSE: 464.69412 = 35

 RMSE: 464.69412 = 36

 RMSE: 464.69412 = 37

 RMSE: 464.69412 = 38

 RMSE: 464.69412 = 39

 RMSE: 464.69412 = 40

 RMSE: 464.69412 = 41

 RMSE: 464.69412 = 42

 RMSE: 464.69412 = 43

 RMSE: 464.69412 = 44

 RMSE: 464.69412 = 45

 RMSE: 464.69412 = 46

 RMSE: 464.69412 = 47

 RMSE: 464.69412 = 48

 RMSE: 464.69412 = 49

 RMSE: 464.69412 = 50

 RMSE: 464.69412 = 51

 RMSE: 464.69412 = 52

 RMSE: 464.69412 = 53

 RMSE: 464.69412 = 54

 RMSE: 464.69412 = 55

 RMSE: 464.69412 = 56

 RMSE: 464.69412 = 57

 RMSE: 464.69412 = 58

 RMSE: 464.69412 = 59

 RMSE: 464.69412 = 60

 RMSE: 464.69412 = 61

 RMSE: 464.69412 = 62

 RMSE: 464.69412 = 63

 RMSE: 464.69412 = 64

 RMSE: 464.69412 = 65

 RMSE: 464.69412 = 66

 RMSE: 464.69412 = 67

 RMSE: 464.69412 = 68

 RMSE: 464.69412 = 69

 RMSE: 464.69412 = 70

 RMSE: 464.69412 = 71

 RMSE: 464.69412 = 72

 RMSE: 464.69412 = 73

 RMSE: 464.69412 = 74

 RMSE: 464.69412 = 75

 RMSE: 464.69412 = 76

 RMSE: 464.69412 = 77

 RMSE: 464.69412 = 78

 RMSE: 464.69412 = 79

 RMSE: 464.69412 = 80

 RMSE: 464.69412 = 81

 RMSE: 464.69412 = 82

 RMSE: 464.69412 = 83

 RMSE: 464.69412 = 84

 RMSE: 464.69412 = 85

 RMSE: 464.69412 = 86

 RMSE: 464.69412 = 87

 RMSE: 464.69412 = 88

 RMSE: 464.69412 = 89

 RMSE: 464.69412 = 90

 RMSE: 464.69412 = 91

 RMSE: 464.69412 = 92

 RMSE: 464.69412 = 93

 RMSE: 464.69412 = 94

 RMSE: 464.69412 = 95

 RMSE: 464.69412 = 96

 RMSE: 464.69412 = 97

 RMSE: 464.69412 = 98

 RMSE: 464.69412 = 99

In [ ]:
test = np.array([0,]).reshape(1, -1)
    print(regressor.predict(test))

In [17]:
    all_crops = {}
    cnt = 0

    for i in range(len(df)):
            all_commodities[df.loc[i]['Cost_Production']] = cnt
            cnt += 1
    print(all_crops)

{}

In [16]:
df.loc[1]['Cost_Production']

12515.81

In [22]:
all_commodities[x[10][0]]

0